### ISSUE TITLE
NHibernate query batch breaks NHibernate.Extensions

### ISSUE THREAD

**Issue by igitur** [maca88/NHibernate.Extensions#16]
It looks like the new query batch which obsoletes multi-query totally breaks NHibernate.Extensions. I don't have a fix yet, but this is a placeholder issue in the meantime. Maybe you have some ideas?

**Comment by maca88** [comment]
I've made a PR that works on the current NHibernate master branch, give it a try and let me know if it works for your cases too.

**Comment by igitur** [comment]
Yes, that PR seems to work. But it seems the new query batcher isn't used, am I right? 

My next step was to try to create a PR to enable caching for fetches and, as far as I understand, that will be available in NH5.2 only with the query batcher. Please correct me if I'm wrong.

**Comment by maca88** [comment]
> But it seems the new query batcher isn't used, am I right?

Not really, the `IncludeLinqProvider` is just a wrapper to the `DefaultQueryProvider`, which uses the new query batcher (in NH 5.2) even in the obsolete [ExecuteFutureValue](https://github.com/nhibernate/nhibernate-core/blob/master/src/NHibernate/Linq/DefaultQueryProvider.cs#L145) and [ExecuteFuture](https://github.com/nhibernate/nhibernate-core/blob/master/src/NHibernate/Linq/DefaultQueryProvider.cs#L132) methods.

> enable caching for fetches and, as far as I understand, that will be available in NH5.2 only with the query batcher. Please correct me if I'm wrong.

I did some research and caching queries that are using `Fetch` and `FetchMany` methods will not work even with the new query batcher. The new query batcher solves the problem of caching future queries but not fetches, they are a completely different story.
Example:
```
[Test]
public void CanBeCombinedWithFetch2()
{
  Sfi.Statistics.Clear();
  Sfi.EvictQueries();

  List<Order> orders;

  using (var s = Sfi.OpenSession())
  using (var t = s.BeginTransaction())
  {
    orders = s.Query<Order>()
            .WithOptions(o => o.SetCacheable(true))
            .Fetch(x => x.Customer)
            .ToList();

    t.Commit();
  }

  Assert.DoesNotThrow(
    () =>
    {
      var name = orders.First().Customer.ContactName;
    });

  using (var s = Sfi.OpenSession())
  using (var t = s.BeginTransaction())
  {
    orders = s.Query<Order>()
            .WithOptions(o => o.SetCacheable(true))
            .Fetch(x => x.Customer)
            .ToList();

    t.Commit();
  }

  Assert.DoesNotThrow(
    () =>
    {
      var name = orders.First().Customer.ContactName; // Throws as customers were not loaded from the cache
    });
}
```
The above query will cache only the `Order` ids, their customers will not be cached, producing an exception when trying to get the customer the second time.

**Comment by igitur** [comment]
> Not really, the IncludeLinqProvider is just a wrapper to the DefaultQueryProvider, which uses the new query batcher (in NH 5.2) even in the obsolete ExecuteFutureValue and ExecuteFuture methods.

From what I can tell `IncludeLinqProvider` is casted to `INhQueryProvider`, which makes line https://github.com/nhibernate/nhibernate-core/blob/master/src/NHibernate/Linq/LinqExtensionMethods.cs#L2430 evaluate to `false`. This is for `ToFutureValue`. For `ToFuture` it works and the batcher is used. I'm not sure why `source.Provider` is different in that case.

Here's a test case that I modified:
```c#
[TestMethod]
public void using_then_include()
{
    EQBPerson petra;

    /*NHibernate way*/
    using (var session = NHConfig.OpenSession())
    {
        var future = session.Query<EQBPerson>()
            .Fetch(o => o.BestFriend)
                .ThenFetch(o => o.IdentityCard)
            .Fetch(o => o.BestFriend)
                .ThenFetch(o => o.BestFriend)
                .ThenFetch(o => o.BestFriend)
                .ThenFetch(o => o.BestFriend)
            .FetchMany(o => o.CurrentOwnedVehicles)
                .ThenFetchMany(o => o.Wheels)
            .FetchMany(o => o.CurrentOwnedVehicles)
                .ThenFetchMany(o => o.RoadworthyTests)
            .FetchMany(o => o.CurrentOwnedVehicles)
                .ThenFetchMany(o => o.MileageHistory)
            .Fetch(o => o.DrivingLicence)
            .Fetch(o => o.CreatedBy)
            .Fetch(o => o.IdentityCard)
            .Fetch(o => o.MarriedWith)
            .FetchMany(o => o.OwnedHouses)
            .FetchMany(o => o.PreviouslyOwnedVehicles)
            .Where(o => o.Name == "Petra")
            .ToFutureValue();
        petra = future.Value;
    }
    ValidateGetEntityResult(petra);

    using (var session = NHConfig.OpenSession())
    {
        var stats = session.SessionFactory.Statistics;
        stats.Clear();
        var future = session.Query<EQBPerson>()
            .Include(o => o.BestFriend.IdentityCard)
            .Include(o => o.BestFriend.BestFriend.BestFriend.BestFriend)
            .Include(o => o.CurrentOwnedVehicles).ThenInclude(o => o.Wheels)
            .Include(o => o.CurrentOwnedVehicles).ThenInclude(o => o.RoadworthyTests)
            .Include(o => o.CurrentOwnedVehicles).ThenInclude(o => o.MileageHistory)
            .Include(o => o.DrivingLicence)
            .Include(o => o.CreatedBy)
            .Include(o => o.IdentityCard)
            .Include(o => o.MarriedWith)
            .Include(o => o.OwnedHouses)
            .Include(o => o.PreviouslyOwnedVehicles)
            .Where(o => o.Name == "Petra")
            .ToFutureValue();
        petra = future.Value;
        CheckStatistics(stats, 5);
    }
    ValidateGetEntityResult(petra);
}
```
The "NHibernate" way uses the query batcher for `ToFutureValue`, but using the "Include" way does not.

**Comment by maca88** [comment]
You are right, [I removed](https://github.com/maca88/NHibernate.Extensions/pull/17/commits/df58091094a7ffe9e463cecd6b1d0154143c1e9f) the `ToFuture`/`ToFutureValue` calls and used `ExecuteFuture`/`ExecuteFutureValue` instead. In addition the usage of reflection was reduced and immutability of queries fixed.

**Comment by maca88** [comment]
@igitur FYI, with NH 5.3 we will be able to cache fetched relations nhibernate/nhibernate-core/issues/1195.
