### ISSUE TITLE
Why did you unlisted the package in nuget.org? Any bugs?

### ISSUE THREAD

**Issue by renanaraujo** [maca88/NHibernate.Extensions#2]
Nuget: https://www.nuget.org/packages/NHibernateAsync.Extensions

**Comment by maca88** [comment]
This package was deprecated and replaced by `NHibernateX.Extensions` package which will be soon deprecated too when NHibernate 5 will arrive. If you are using a normal version of NHibernate then you need to use `NHibernate.Extensions` package (without X)

**Comment by renanaraujo** [comment]
Thanks @maca88 !
