### ISSUE TITLE
With Npgsql (Postgres NH driver), the lack of DeepClone async implementation prevents using it with other async calls on the same ISession.

### ISSUE THREAD

**Issue by MathieuDSTP** [maca88/NHibernate.Extensions#20]
I am using Npgsql dotnet driver for postgres. As per their documentation and general C# guidelines, breaking async with non-async calls for IO-bound calls can create deadlocks. Even though the issue is not strictly related to this, the last comment in the thread makes it clear. https://github.com/npgsql/npgsql/issues/1232.

I have implemented/adapted some async methods with their tests to provide for a full async pipeline if the db driver requires it.
I have created a pull request #19 for your review. Thank you for considering.

When within a a single ISession I make async calls, then synchronous calls and then go back to async calls, Npgsql throws (or not, depending of the current thread scheduling).
With these async additions, the ISession can be used continuously asynchronously and work all the times with Npgsql.
I suspect that this problem could be observed with other db drivers, depending on their implementation.

**Comment by MathieuDSTP** [comment]
While testing, I also notice that there a few obsolete calls as per latest NH version. You may want to look at it.

**Comment by maca88** [comment]
The project is now updated to target NHibernate 5.3.0 and obsolete calls were updated. The async methods are now available in version `3.0.0`.
