### ISSUE TITLE
Element maps

### ISSUE THREAD

**Issue by igitur** [maca88/NHibernate.Extensions#5]
In #4 I implement **entity** maps, but I also have projects with **element** maps, e.g. `public virtual IDictionary<DateTime, double> SomeTimeSeries {get; set;}` that I map as `.AsMap<DateTime>(o => o.TimeSeries).KeyColumn("EffectiveDate").Element("Value")`

I'm creating an issue in the meantime, but I will see whether I can solve it later.

**Comment by maca88** [comment]
I see what has to be corrected to support it, I will make a PR this.

**Comment by igitur** [comment]
I just completed a PR. It depends on #4. If you think of a different approach you can close it.
