### ISSUE TITLE
.NET 4.5 build

### ISSUE THREAD

**Issue by igitur** [maca88/NHibernate.Extensions#8]
Before I work on a PR, are you OK with the idea of doing a .NET 4.5 build, based on NH4? 

In the PR I will upgrade the `.csproj` files to the newer VS2017 format and use multi-framework targeting and conditional includes to target either NH5 (for the net461 build) or NH4 (for the net45 build).

**Comment by maca88** [comment]
I am ok with it :)

**Comment by igitur** [comment]
Ok, I'll go ahead. So would you want to release the 2 builds as separate NuGet packages or as 1 NuGet package targeting different frameworks?

**Comment by maca88** [comment]
I would have one NuGet package where `1.x.x` version would be for NH4 and `2.x.x` version for NH5, is that ok for you?

**Comment by igitur** [comment]
Yes, that makes sense.

**Comment by igitur** [comment]
I've decided it's just easier to upgrade my projects to NH5 that bother with this further. Thanks for your input anyway.

Any chance of a NuGet release for the NH5 support?

**Comment by maca88** [comment]
I've released the current master to NuGet as version `2.0.0`.

**Comment by igitur** [comment]
Awesome, thanks.
